tricks/blueprints/creatures.py
from logging import getLogger
from operator import attrgetter
from typing import Any, Callable, Iterable, List, Sequence, Tuple

import flask
import inflect
import natsort

from tricks.loaders.beyond import Beyond
from tricks.loaders.beyond.characters import BeyondCharacterLoader
from tricks.loaders.beyond.monsters import BeyondMonsterLoader
from tricks.loaders.custom import CustomCharacterLoader, CustomMonsterLoader
from tricks.models.creature import Character
from tricks.models.creatures import Page
from tricks.modules.index import CachedIndex

log = getLogger(__name__)

inflect_engine = inflect.engine()

blueprint = flask.Blueprint("creatures", __name__, url_prefix="/creatures")


@blueprint.before_app_first_request
def before_first_request():
    beyond = Beyond.configure(flask.current_app)

    flask.current_app.loaders = {
        "beyond/monster": BeyondMonsterLoader(beyond),
        "beyond/character": BeyondCharacterLoader(beyond),
        "custom/character": CustomCharacterLoader(),
        "custom/monster": CustomMonsterLoader(),
    }

    flask.current_app.creatures_cache = CachedIndex("creatures", Page)


@blueprint.route("/<string:section>/<string:page>/tents")
def tents(section: str, page: str):
    index = flask.current_app.creatures_cache.index
    return flask.render_template(
        "creatures_tents.html.j2", section=index[section], page=index[section][page]
    )


@blueprint.route("/<string:section>/<string:page>/encounters")
def encounters(section: str, page: str):
    index = flask.current_app.creatures_cache.index
    return flask.render_template(
        "creatures_encounters.html.j2",
        section=index[section],
        page=index[section][page],
    )


@blueprint.route("/<string:section>/<string:page>/summary")
def summary(section: str, page: str):
    index = flask.current_app.creatures_cache.index
    return flask.render_template(
        "creatures_summary.html.j2", section=index[section], page=index[section][page]
    )


@blueprint.route("/<string:section>/<string:page>/list")
def lists(section: str, page: str):
    index = flask.current_app.creatures_cache.index
    return flask.render_template(
        "creatures_list.html.j2", section=index[section], page=index[section][page]
    )


@blueprint.route("/tents")
def blank():
    return flask.render_template("tents_blank.html.j2")


@blueprint.app_template_filter()
def titlecase(_string):
    return None


@blueprint.add_app_template_test
def character(obj):
    return isinstance(obj, Character)


def partition(iterable: Iterable, func: Callable) -> Tuple[Iterable, Iterable]:
    left: List = []
    right: List = []
    for item in iterable:
        (left if func(item) else right).append(item)
    return left, right


@blueprint.app_template_filter()
def natural_sort(iterable: Iterable[Any], *attributes: str) -> Sequence[Any]:
    getter = attrgetter(*attributes)
    unsortable, sortable = partition(iterable, lambda x: getter(x) is None)
    return [*unsortable, *natsort.natsorted(sortable, key=getter)]


@blueprint.app_template_filter()
def counted_groups_of(iterable, size):
    group = []
    groups = []
    for creature in iterable:
        if (sum(c.count for c in group) + creature.count) < size:
            group.append(creature)
        else:
            groups.append(group)
            group = [creature]

    if group:
        groups.append(group)

    return groups


@blueprint.app_template_filter()
def plural(name: str, count: int) -> str:
    return inflect_engine.plural(name, count)

tricks/blueprints/toc.py
import pathlib

import flask

from tricks.utils import paginate_by_size

blueprint = flask.Blueprint("toc", __name__)
blueprint.add_app_template_filter(paginate_by_size)


@blueprint.route("/")
def toc():
    return flask.render_template(
        "toc.html.j2",
        creatures=flask.current_app.creatures_cache.index,
        items=flask.current_app.items_cache.index,
    )


@blueprint.route("/images/<path:filename>")
@blueprint.route("/creatures/images/<path:filename>")
def base_static(filename):
    directory = pathlib.Path(flask.current_app.config["APP_DIRECTORY"]) / "images"
    return flask.send_from_directory(str(directory), filename)

tricks/templates/base.html.j2
{%- from "macros.html.j2" import render_bestiary_section -%}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DMTools{% if title is defined %} | {{ title }}{% endif %}</title>
  <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename='rpg-awesome-raw/ra-book.svg') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='rpg-awesome/css/rpg-awesome.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">
</head>
<body class="A4 {% if landscape is defined %}landscape{% else %}portrait{% endif %}">
<div class="screen-only">
  <nav class="navbar navbar-primary">
    <div class="navbar-columns container">
      <div class="navbar-brand">
        <a href="{{ url_for('toc.toc') }}" class="navbar-item navbar-brand" title="Return to homepage">
          <i class="ra ra-book"></i>
          <span>The Book of Tricks</span>
        </a>
      </div>
      <div class="navbar-links">
        {% block links %}
        {% endblock %}
      </div>
      <div>
        <a href="{{ url_for("toc.toc") }}" class="navbar-item" title="Return to table of contents">{{ title }}</a>
      </div>
    </div>
  </nav>
  <nav class="navbar navbar-secondary">
    {% block pages %}
      <div class="navbar-columns container">
        <div>
          {% if page is defined %}
            <a href="#" class="navbar-item">{{ page.name }}</a>
          {% endif %}
        </div>
        <div>
          {% if pages is defined %}
            {% for _ in pages %}
              <a href="#{{ loop.index }}" class="navbar-item">{{ loop.index }}</a>
            {% endfor %}
          {% endif %}
        </div>
        <div>
          {% if section is defined %}
            <a href="#" class="navbar-item">{{ section.name }}</a>
          {% endif %}
        </div>
      </div>
    {% endblock %}
  </nav>
</div>
{% block body %}#u
{% endblock body %}
{% if config['LIVE_RELOAD'] %}
  <script src="http://localhost:35729/livereload.js?snipver=1"></script>
{% endif %}
</body>
</html>

tricks/templates/base_creatures.html.j2
{% extends 'base.html.j2' %}

{% block links %}
  <a title="Creature tents" href="{{ url_for('creatures.tents', section=section.slug, page=page.slug) }}" class="navbar-item link-tents"><i class="ra ra-bird-claw"></i></a>
  <a title="Encounter sheet" href="{{ url_for('creatures.encounters', section=section.slug, page=page.slug) }}" class="navbar-item link-encounter"><i class="ra ra-scroll-unfurled"></i></a>
  <a title="Character sheet" href="{{ url_for('creatures.summary', section=section.slug, page=page.slug) }}" class="navbar-item link-summaries"><i class="ra ra-crossed-swords"></i></a>
  <a title="Creature lists" href="{{ url_for('creatures.lists', section=section.slug, page=page.slug) }}" class="navbar-item link-lists"><i class="ra ra-book"></i></a>
{% endblock %}

tricks/templates/creatures_encounters.html.j2
{% extends 'base_creatures.html.j2' %}

{% from 'macros.html.j2' import class, empty, source %}
{% from 'macros_creatures.html.j2' import modified %}

{% set title = "Encounters" %}
{% set pages = page.paged_encounters(33) %}

{% set show_encounter_area = page.areas()|length > 1 %}
{% set show_encounter_names = page.encounter_names()|length > 1 %}
{% set show_sources = page.sources()|length > 1 %}
{% set show_separate_monster_manual_references = False %}

{% block body %}
  {% for encounters in pages %}
    <section id="{{ loop.index }}" class="sheet">
      <div class="encounters">
        <main>
          <h1>
            <a href="#{{ loop.index }}">{{ section.name }}</a>
          </h1>
          <h2>
            <a href="#{{ loop.index }}">{{ page.name }}</a>
          </h2>
          <table>
            <tr>
              {% if show_encounter_area %}
                <th class="number">#</th>
              {% endif %}
              {% if show_encounter_names %}
                <th class="text encounter">Encounter</th>
              {% endif %}
              <th class="text creature">Creature</th>
              <th class="number challenge-rating">CR</th>
              <th class="number initiative">In</th>
              <th class="number armour_class">AC</th>
              <th class="hit-points" colspan="3">Hit points</th>
              <th class="status">Status</th>
              {% if show_sources %}
                <th class="source" colspan="{{ 2 if show_separate_monster_manual_references else 1 }}">Source</th>
              {% endif %}
            </tr>
            {% for encounter in encounters %}
              {% set encounter_loop = loop %}
              {% for ref in encounter.creatures %}
                {% set ref_loop = loop %}
                {% for n in range(0, ref.count) %}
                  {% set creature_loop = loop %}
                  <tr class="creature {{ 'creature-modified' if ref.creature.original else 'creature-unmodified' }}">
                    {% if ref_loop.first and creature_loop.first %}
                      {% if show_encounter_area %}
                        <td class="number reference" rowspan="{{ encounter.count }}">{{ encounter.area or '' }}</td>
                      {% endif %}
                      {% if show_encounter_names %}
                        <td class="text location" rowspan="{{ encounter.count }}">{{ encounter.name }}</td>
                      {% endif %}
                    {% endif %}

                    {% if creature_loop.first %}
                      <td class="text creature-details" rowspan="{{ ref.count }}">
                        {% call(value) modified(ref.creature.compare('name')) %}
                          <a href="{{ ref.creature.url }}">{{ ref.creature.name|plural(ref.count) }}</a>
                        {% endcall %}
                      </td>
                    {% endif %}

                    <td class="number challenge-rating">
                      {%- call(value) modified(ref.creature.compare('challenge_rating')) -%}
                        {{ ref.creature.challenge_rating_unicode() }}
                      {%- endcall -%}
                    </td>
                    <td class="number initiative">
                      {%- call(value) modified(ref.creature.compare('dexterity.modifier')) -%}
                        {{ value }}
                      {%- endcall -%}
                    </td>
                    <td class="number armour-class">
                      {%- call(value) modified(ref.creature.compare('armour_class')) -%}
                        {{ value or empty() }}
                      {%- endcall -%}
                    </td>
                    <td class="number hit-points min">
                      {%- call(value) modified(ref.creature.compare('min_hit_points')) -%}
                        {{ value or empty() }}
                      {%- endcall -%}
                    </td>
                    <td class="number hit-points avg">
                      {%- call(value) modified(ref.creature.compare('avg_hit_points')) -%}
                        {{ value or empty() }}
                      {%- endcall -%}
                    </td>
                    <td class="number hit-points max">
                      {%- call(value) modified(ref.creature.compare('max_hit_points')) -%}
                        {{ value or empty() }}
                      {%- endcall -%}
                    </td>

                    <td class="text-description status">
                      {{ ref.settings.notes|markdown if ref.settings.notes is not none else '' }}
                    </td>

                    {% if creature_loop.first and show_sources %}
                      {% if show_separate_monster_manual_references %}
                        {% if ref.creature.is_from_monster_manual %}
                          <td class="source" rowspan="{{ ref.count }}"></td>
                          <td class="source" rowspan="{{ ref.count }}">{{ source(ref.creature) }}</td>
                        {% elif ref.creature.original %}
                          <td class="source" rowspan="{{ ref.count }}">{{ source(ref.creature) }}</td>
                          <td class="source" rowspan="{{ ref.count }}">{{ source(ref.creature.original) }}</td>
                        {% else %}
                          <td class="source" rowspan="{{ ref.count }}">{{ source(ref.creature) }}</td>
                          <td class="source" rowspan="{{ ref.count }}"></td>
                        {% endif %}
                      {% else %}
                        {% if ref.creature.reference %}
                          <td class="source" rowspan="{{ ref.count }}">{{ source(ref.creature) }}</td>
                        {% elif ref.creature.original and ref.creature.original.reference %}
                          <td class="source" rowspan="{{ ref.count }}">{{ source(ref.creature.original) }}</td>
                        {% else %}
                          <td class="source" rowspan="{{ ref.count }}"></td>
                        {% endif %}
                      {% endif %}
                    {% endif %}
                  </tr>
                {% endfor %}
              {% endfor %}
            {% endfor %}
          </table>
        </main>
      </div>
    </section>
  {% endfor %}
{% endblock %}

tricks/templates/creatures_list.html.j2
{% extends 'base_creatures.html.j2' %}

{% from 'macros.html.j2' import class, empty, numeric_empty, source %}
{% from 'macros_creatures.html.j2' import modified %}

{% set title = "Creature list" %}
{% set pages = page.encounters %}

{% block body %}
  <section class="sheet">
    <main class="summary encounters">
      <div>
        <h1>
          {{ section.name }}
        </h1>
        <h2>
          {{ page.name }}
        </h2>
        {% for encounter in pages %}
          <div id="{{ loop.index }}">
            <h3><a href="#{{ loop.index }}">{{ encounter.name }}</a></h3>
            <p>
              {% for ref in encounter.creatures %}
                <a href="{{ ref.creature.url }}">{{ ref.creature.name }}</a>
                {%- if loop.last %}.{% else %}, {% endif -%}
              {% endfor %}
            </p>
          </div>
        {% endfor %}
      </div>
    </main>
  </section>
{% endblock %}

tricks/templates/creatures_summary.html.j2
{% extends 'base_creatures.html.j2' %}

{% from 'macros.html.j2' import class, empty, numeric_empty, source %}
{% from 'macros_creatures.html.j2' import modified %}

{% set title = "Character sheet" %}
{% set pages = page.paged_encounters(32) %}

{% block body %}
  {% for encounters in pages %}
    <section id="{{ loop.index }}" class="sheet">
      <main class="summary encounters">
        <div>
          <h1>
            <a href="#{{ loop.index }}">{{ section.name }}</a>
          </h1>
          <h2>
            <a href="#{{ loop.index }}">{{ page.name }}</a>
          </h2>
          <table>
            <tbody>
            {% for encounter in encounters %}
              {% for ref in encounter.creatures %}
                {% if ref.creature is character %}
                  <tr class="character {{ class('theme', ref.creature.theme) }}">
                    <td class="character-name">
                      {{ ref.creature.name }}
                    </td>
                    <td class="character-type">
                      Level {{ ref.creature.level }} {{ ref.creature.type }}
                    </td>
                    <td class="stat">
                      <span class="name">AC</span>
                      <span class="value">
                        {% call(value) modified(ref.creature.compare('armour_class')) %}
                          {{ numeric_empty(value) }}
                        {% endcall %}
                      </span>
                    </td>
                    <td class="stat">
                      <span class="name">HP</span>
                      <span class="value">
                        {% call(value) modified(ref.creature.compare('avg_hit_points')) %}
                          {{ numeric_empty(value) }}
                        {% endcall %}
                      </span>
                    </td>
                    <td class="stat">
                      <span class="name">SS</span>
                      <span class="value">
                        {% call(value) modified(ref.creature.compare('spell_save_dc')) %}
                          {{ numeric_empty(value) }}
                        {% endcall %}
                      </span>
                    </td>
                    <td class="stat">
                      <span class="name">PP</span>
                      <span class="value">
                        {% call(value) modified(ref.creature.compare('passive_perception')) %}
                          {{ numeric_empty(value) }}
                        {% endcall %}
                      </span>
                    </td>
                    <td class="character-player">
                      {{ ref.creature.player }}
                    </td>
                  </tr>
                  <tr class="character {{ class('theme', ref.creature.theme) }}">
                    <td class="notes" colspan="7">
                      {{ ref.settings.notes|markdown if ref.settings.notes is not none else '' }}
                    </td>
                  </tr>
                  <tr class="break">

                  </tr>
                {% else %}
                  <tr>
                    <td colspan="7">
                      {{ ref.creature.name }} is not a character.
                    </td>
                  </tr>
                {% endif %}
              {% endfor %}
            {% endfor %}
            </tbody>
          </table>
        </div>
      </main>
    </section>
  {% endfor %}
{% endblock %}

tricks/templates/creatures_tents.html.j2
{% extends 'base_creatures.html.j2' %}

{% from 'tents_monster.html.j2' import monster %}
{% from 'tents_character.html.j2' import character %}

{% set title = 'Creature tents' %}
{% set pages = page.tents(5) %}
{% set landscape = True %}

{% block title %}
  Creatures from
  <a href="#">{{ page.name }}</a> in the
  <a href="{{ url_for('toc.toc') }}">{{ section.name }}</a> section
{% endblock %}

{% block body %}
  {% for tents in pages %}
    <div class="sheet centered tents">
      <div class="tents-grid">
        {% for tent in tents %}
          {% if tent.creature is character %}
            {{ character(tent) }}
          {% else %}
            {{ monster(tent) }}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  {% endfor %}
{% endblock %}

tricks/templates/flask_debugtoolbar_creatures.html.j2
<div>
  <table>
    {% for creature in creatures %}
      <tr>
        <td>{{ loop.index }}</td>
        <td><a href="#debug-{{ creature.slug }}">{{ creature.name }}</a></td>
      </tr>
    {% endfor %}
  </table>
</div>

<div>
  {% for creature in creatures %}
    <div id="debug-{{ creature.slug }}">
      <h4>
        {{ creature.name }}
      </h4>

      <table>
        <thead>
        <tr>
          <th>Property</th>
          <th>Value</th>
        </tr>
        </thead>

        {% for key, value, raw in creature.debug() %}
          <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
            <td>{{ raw }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  {% endfor %}
</div>

tricks/templates/macros.html.j2
{#- Non-breaking space: &#160; -#}
{%- macro joiner() %} {%- endmacro -%}

{%- macro enabled(value) -%}
  {{ 'enabled' if value else 'disabled' }}
{%- endmacro -%}

{%- macro comma(loop) -%}
  {%- if not loop.last %}, {% endif -%}
{%- endmacro -%}

{%- macro empty() -%}
  <span class="none disabled">--</span>
{%- endmacro -%}

{%- macro numeric_empty(value) -%}
  {%- if value -%}
    {{ value }}
  {%- elif value == 0 -%}
    --
  {%- endif -%}
{%- endmacro -%}

{%- macro value_or_empty(value) -%}
  {% if value %}
    {{ value }}
  {% else %}
    {{ empty() }}
  {% endif %}
{%- endmacro -%}

{%- macro slug(text) -%}
  {{ text|replace(' ', '-')|lower }}
{%- endmacro -%}

{%- macro class(base, text) -%}
  {{ base }}-{{ slug(text) }}
{%- endmacro -%}

{%- macro classes(base, items) -%}
  {%- for item in items -%}
    {{- class(base, item) -}}
    {{- ' ' -}}
  {%- endfor -%}
{%- endmacro -%}

{%- macro source(creature) -%}
  {%- if creature.reference -%}
    <a class="reference" href="{{ creature.url }}">{{- creature.reference -}}</a>
  {%- endif -%}
{%- endmacro -%}

{%- macro render_bestiary_section(section, parts, level=0) -%}
  <ul class="section section-level-{{ level }}">
    {% for subsection_id, subsection in section %}
      {% set subsection_link = parts|list + [subsection_id] %}
      {% set section_level = level + 1 %}
      {% if subsection is iterable %}
        <li>
          <div class="subsection subsection-level-{{ section_level }}">
            <span class="subsection-name">
              <a class="" title="Encounter sheet for {{ subsection_id|titlecase }}" href="{{ url_for('bestiary.encounter', section=subsection_link) }}">{{ subsection_id|titlecase }}</a>
            </span>
            <span class="subsection-links">
              <a class="link-encounter" title="Encounter sheet for {{ subsection_id|titlecase }}" href="{{ url_for('bestiary.encounter', section=subsection_link) }}"><i class="ra ra-sword"></i>️</a>
              <a class="link-tents" title="Creature tents for {{ subsection_id|titlecase }}" href="{{ url_for('bestiary.tents', section=subsection_link) }}"><i class="ra ra-wyvern"></i></a>
            </span>
          </div>
          {{ render_bestiary_section(subsection, parts=subsection_link, level=section_level) }}
        </li>
      {% endif %}
    {% endfor %}
  </ul>
{%- endmacro -%}

tricks/templates/macros_creatures.html.j2
{% from 'macros.html.j2' import empty %}

{%- macro modified(result) -%}
  {%- set is_modified, new = result -%}
  {%- set text = caller(new) if caller is defined else new -%}
  {%- if is_modified -%}
    <span class="modified">{{ text or empty() }}</span>
  {%- else -%}
    <span class="unmodified">{{ text or empty() }}</span>
  {%- endif -%}
{%- endmacro -%}

tricks/templates/tents_character.html.j2
{% from 'tents_creature.html.j2' import image %}
{% from 'macros.html.j2' import class, classes, empty, numeric_empty %}

{%- macro character_description(character) -%}
  {% if character.level %}Level {{ character.level }}{% endif %} {{ character.type|title }}
{%- endmacro -%}

{% macro character(ref) %}
  {%- set character = ref.creature -%}
  <div class="creature character {{ class('source', character.source) }} {{ class('campaign', character.campaign) }} {{ class('theme', character.theme) }} {{ classes('creature', ref.settings.classes) }}">
    <div class="box front">
      <div class="image">
        {{ image(character.image) }}
      </div>
      <div class="name">
        {{ character.name }}
      </div>
      <div class="description">
        {{ character_description(character) }}
      </div>
    </div>
    <div class="box back header">
      <span class="name">{{ character.name }}</span>
      <span class="description">{{ character_description(character) }}</span>
      <span class="armour-class">{{ numeric_empty(character.armour_class) }}</span>
      <span class="armour-class-caption">AC</span>
    </div>
    <div class="box back form details">
      <div class="brick">
        <input type="text" value="{{ numeric_empty(character.hit_points) }}" title="Hit Points">
        <label>Hit Points</label>
      </div>

      <div class="brick">
        <input type="text" value="{{ numeric_empty(character.armour_class) }}" title="Armour Class">
        <label>Armour Class</label>
      </div>

      <div class="brick">
        <input type="text" value="{{ numeric_empty(character.spell_save_dc) }}" title="Spell Save DC">
        <label>Spell Save DC</label>
      </div>

      <div class="brick">
        <input type="text" value="{{ numeric_empty(character.passive_perception) }}" title="Passive Perception">
        <label>Passive Perception</label>
      </div>

      <div class="brick wide">
        {% if ref.settings.notes %}
          <div class="notes">{{ ref.settings.notes|markdown }}</div>
        {% endif %}
      </div>
    </div>
    <div class="box back details text footer">
      <div class="property">
        {% if character.campaign %}
          <span class="value">{{ character.campaign }}</span>
        {% endif %}
      </div>
      <div class="property">

      </div>
      <div class="property">
        {% if character.player %}
          <strong class="value">{{ character.player }}</strong>
        {% endif %}
      </div>
    </div>
  </div>
{% endmacro %}

tricks/templates/tents_creature.html.j2
{% from 'macros.html.j2' import enabled, comma, empty, value_or_empty, class %}
{% from 'macros_creatures.html.j2' import modified %}

{% macro image(url) %}
  {% if url %}
    <img src="{{ url }}" alt="">
  {% endif %}
{% endmacro %}

{%- macro attribute(name) -%}
  {# Display a tidbit, e.g. Languages. #}
  {# Should have no punctuation after the name. #}
  <span class="property">
    <span class="name">{{ name }}</span>
    <span class="value">{{ caller() }}</span>
  </span>
{%- endmacro -%}

{%- macro attribute_dict(name, dictionary) -%}
  {% if dictionary %}
    <span class="property">
      <span class="name">{{ name }}</span>
      <span class="value">
        {%- for key, value in dictionary.items() -%}
          {{ caller(key, value).strip() }}
          {%- if not loop.last %}, {% endif -%}
        {%- endfor -%}
      </span>
    </span>
  {% endif %}
{%- endmacro -%}

{% macro attributes(creature) %}
  <div class="stats attributes">
    {%- macro stat(name, class=None) -%}
      <span class="stat attribute name {{ class }}">{{ name }}</span>
      <span class="stat attribute value {{ class }}">{{ caller() }}</span>
    {%- endmacro -%}
    {% call stat('AC', 'armour_class') %}
      {{ value_or_empty(modified(creature.compare('armour_class'))) }}
    {% endcall %}
    {% call stat('Hit dice', 'hit_dice') %}
      {{ value_or_empty(modified(creature.compare('hit_dice'))) }}
    {% endcall %}
    {% call stat('Hit points', 'hit_points') -%}
      {% call(value) modified(creature.compare('min_hit_points')) %}
        <span class="min">{{ value_or_empty(value) }}</span>
      {% endcall %}
      {% call(value) modified(creature.compare('avg_hit_points')) %}
        <span class="avg">{{- value_or_empty(value) -}}</span>
      {% endcall %}
      {% call(value) modified(creature.compare('max_hit_points')) %}
        <span class="max">{{ value_or_empty(value) }}</span>
      {% endcall %}
    {%- endcall %}
    {% call stat('Speed', 'speed') -%}
      {% if creature.speed %}
        {% call(value) modified(creature.compare('speed')) %}
          <span>{{ creature.speed.value }} ft.</span>
        {% endcall %}
      {% else %}
        {{ empty() }}
      {% endif %}
    {%- endcall %}
  </div>
{% endmacro %}

{% macro abilities(creature) %}
  <div class="stats abilities">
    {% for name, ability in creature.abilities().items() %}
      <div class="stat ability name {{ name|lower }}">{{ name|upper }}</div>
      <div class="stat ability value {{ name|lower }}">
        {% if ability is none %}
          {{ empty() }}
        {% else %}
          <span class="modifier {{ enabled(ability.modifier) }}">
            {{ ability.modifier }}
          </span>
          {% if ability.saving_throw %}
            <span class="saving-throw">
              ({{ ability.saving_throw }})
            </span>
          {% endif %}
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endmacro %}

tricks/templates/toc_creatures.html.j2
{% macro toc_page_creatures(creatures) %}
  <div class="sheet">
    <nav class="creatures">
      <h2 id="creatures"><a href="#creatures">Creatures</a></h2>
      <ul class="tree">
        {% for section in creatures %}
          <li id="creatures-{{ section.slug }}" class="tree-section">
            <a href="#creatures-{{ section.slug }}" class="tree-header">{{ section.name }}</a>
            <ul>
              {% for page in section %}
                <li class="tree-page flex">
                  <span>
                    <a href="{{ url_for('creatures.tents', section=section.slug, page=page.slug) }}" class="link-creature">{{ page.name }}</a>
                  </span>
                  <span class="links">
                    <a title="Creature tents" href="{{ url_for('creatures.tents', section=section.slug, page=page.slug) }}" class="link-tents"><i class="ra ra-bird-claw"></i></a>
                    <a title="Encounter sheet" href="{{ url_for('creatures.encounters', section=section.slug, page=page.slug) }}" class="link-encounter"><i class="ra ra-scroll-unfurled"></i></a>
                    <a title="Summary sheet" href="{{ url_for('creatures.summary', section=section.slug, page=page.slug) }}" class="link-summaries"><i class="ra ra-crossed-swords"></i></a>
                    <a title="Creature lists" href="{{ url_for('creatures.lists', section=section.slug, page=page.slug) }}" class="link-lists"><i class="ra ra-book"></i></a>
                  </span>
                </li>
              {% endfor %}
            </ul>
          </li>
        {% endfor %}
      </ul>
    </nav>
  </div>
{% endmacro %}

{% macro toc_creatures_summary(creatures) %}
  <nav>
    <h2><a href="#creatures">Creatures</a></h2>
    <p>Monsters and NPCs.</p>
    <ul class="tree">
      <li class="tree-section">
        <span class="tree-header">
          Sections
        </span>
        <ul>
          {% for section in creatures %}
            <li class="tree-page">
              <a href="#creatures-{{ section.slug }}" class="name">{{ section.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </li>
      <li class="tree-section">
        <span class="tree-header">
          Utilities
        </span>
        <ul>
          <li>
            <a href="{{ url_for("creatures.blank") }}" class="name">Blank character tents</a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
{% endmacro %}